apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practice-app
  template:
    metadata:
      labels:
        app: practice-app

    spec:
      containers:
        - name: practice-container
          image: ghcr.io/craztool/practice-app:e7862354343d3ae36d1d01423b4321202210503c
          ports:
          - containerPort: 8080